enum DiveSiteReducerActionsEnum {
    GET_SITES = 'GET_DIVE_SITES',
    GET_USER_SITES = 'GET_USER_SAVED_DIVE_SITES',
    ADD_USER_SAVED_SITE = 'ADD_USER_SAVED_DIVE_SITE',
    CREATE_DIVE_SITE = 'CREATE_DIVE_SITE',
    REMOVE_USER_SAVED_SITE = 'REMOVE_USER_SAVED_DIVE_SITE',
    DELETE_DIVE_SITE = 'DELETE_DIVE_SITE',
    APPLICATION_ERROR = 'APP_ERROR',
    APPLICATION_ERROR_CLEAR = 'APP_ERROR_CLEAR',
    SHOW_POPUP_MODAL = 'SHOW_POPUP_MODAL',
    HIDE_POPUP_MODAL = 'HIDE_POPUP_MODAL'
}

export default DiveSiteReducerActionsEnum;